// frameworks/svelte/src/lib/VistaView.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { vistaView } from 'vistaview';
  import type { VistaOpt, VistaInterface } from 'vistaview';
  import { tick } from 'svelte';

  export let selector: string = '> a';
  export let options: VistaOpt = {} as VistaOpt;
  export let id: string = '';
  export let vistaRef: ((obj: { vistaView: VistaInterface | null; container: HTMLElement | null } | null) => void) | undefined;

  let container: HTMLDivElement | null = null;
  let instance: VistaInterface | null = null;
  const galleryId = id || `vvw-gallery-${Math.random().toString(36).slice(2)}`;

  function destroyInstance() {
    instance?.destroy();
    instance = null;
    vistaRef?.(null);
  }

  function initInstance() {
    if (!container) return;
    destroyInstance();
    instance = vistaView({
      ...options,
      elements: `#${galleryId} ${selector}`,
    });
    vistaRef?.({ vistaView: instance, container });
  }

  // expose API via component instance
  export function getApi() {
    return { vistaView: instance, container };
  }

  // re-init when props change
  $: selector, options, async () => {
    // wait DOM update if necessary
    await tick();
    initInstance();
  };

  onMount(() => {
    initInstance();
  });

  onDestroy(() => {
    destroyInstance();
  });
</script>

<div id={galleryId} bind:this={container} {...$$restProps}>
  <slot />
</div>

// frameworks/solid/src/vistaview.tsx
import { createEffect, onCleanup, onMount, splitProps } from 'solid-js';
import { vistaView } from 'vistaview';
import type { VistaOpt, VistaInterface } from 'vistaview';
import type { JSX } from 'solid-js';

export interface VistaViewProps extends JSX.HTMLAttributes<HTMLDivElement> {
  selector?: string;
  options?: VistaOpt;
  vistaRef?: (instance: VistaInterface | null) => void;
  ref?: (el: HTMLDivElement | undefined) => void;
  id?: string;
  children?: any;
}

export function VistaView(props: VistaViewProps) {
  let container: HTMLDivElement | undefined;
  let instance: VistaInterface | null = null;
  const [local, rest] = splitProps(props, ['selector', 'options', 'vistaRef', 'ref', 'id', 'children']);
  const galleryId = local.id || `vvw-gallery-${Math.random().toString(36).slice(2)}`;

  onMount(() => {
    if (!container) return;
    instance = vistaView({
      ...local.options,
      elements: `#${galleryId} ${local.selector ?? '> a'}`,
    });
    local.vistaRef?.(instance);
    local.ref?.(container);
  });

  createEffect(() => {
    // If options, selector, or children change, re-instantiate
    instance?.destroy();
    instance = vistaView({
      ...local.options,
      elements: `#${galleryId} ${local.selector ?? '> a'}`,
    });
    local.vistaRef?.(instance);
  });

  onCleanup(() => {
    instance?.destroy();
    local.vistaRef?.(null);
    instance = null;
  });

  return (
    <div ref={el => (container = el)} id={galleryId} {...rest}>
      {local.children}
    </div>
  );
}
