// src/VistaView.svelte
<script lang="ts">
import { onMount } from 'svelte';
import { useVistaView } from './svelte';
import type { VistaViewProps } from './svelte';
import type { Snippet } from 'svelte';
import type { HTMLAttributes } from 'svelte/elements';
import type { VistaOpt } from './vistaview';

const { 
  children, 
  id, 
  selector = '> a', 
  ref,
  options,
  ...rest
} = $props<
  VistaViewProps & 
  { options: VistaOpt } &
  { children?: Snippet } & 
  HTMLAttributes<HTMLDivElement>
>();

let vista: ReturnType<typeof useVistaView>;

const initialId = `vvw-gallery-${Math.random().toString(36).slice(2)}`;

onMount(() => {
  const galleryId = id || initialId;

  // Initialize Vista with the computed galleryId and selector.
  vista = useVistaView({
    ...options,
    elements: `#${galleryId} ${selector}`,
  });

  if (ref && vista) Object.assign(ref, vista);
});
</script>

<div {...rest} id={id || initialId}>
  {@render children()}
</div>

// frameworks/solid/src/vistaview.tsx
import { createEffect, onCleanup, onMount, splitProps } from 'solid-js';
import { vistaView } from 'vistaview';
import type { VistaOpt, VistaInterface } from 'vistaview';
import type { JSX } from 'solid-js';

export interface VistaViewProps extends JSX.HTMLAttributes<HTMLDivElement> {
  selector?: string;
  options?: VistaOpt;
  vistaRef?: (instance: VistaInterface | null) => void;
  ref?: (el: HTMLDivElement | undefined) => void;
  id?: string;
  children?: any;
}

export function VistaView(props: VistaViewProps) {
  let container: HTMLDivElement | undefined;
  let instance: VistaInterface | null = null;
  const [local, rest] = splitProps(props, ['selector', 'options', 'vistaRef', 'ref', 'id', 'children']);
  const galleryId = local.id || `vvw-gallery-${Math.random().toString(36).slice(2)}`;

  onMount(() => {
    if (!container) return;
    instance = vistaView({
      ...local.options,
      elements: `#${galleryId} ${local.selector ?? '> a'}`,
    });
    local.vistaRef?.(instance);
    local.ref?.(container);
  });

  createEffect(() => {
    // If options, selector, or children change, re-instantiate
    instance?.destroy();
    instance = vistaView({
      ...local.options,
      elements: `#${galleryId} ${local.selector ?? '> a'}`,
    });
    local.vistaRef?.(instance);
  });

  onCleanup(() => {
    instance?.destroy();
    local.vistaRef?.(null);
    instance = null;
  });

  return (
    <div ref={el => (container = el)} id={galleryId} {...rest}>
      {local.children}
    </div>
  );
}
