// frameworks/solid/src/vistaview.tsx
import { createEffect, onCleanup, onMount, splitProps } from 'solid-js';
import { vistaView } from 'vistaview';
import type { VistaOpt, VistaInterface } from 'vistaview';
import type { JSX } from 'solid-js';

export interface VistaViewProps extends JSX.HTMLAttributes<HTMLDivElement> {
  selector?: string;
  options?: VistaOpt;
  vistaRef?: (instance: VistaInterface | null) => void;
  ref?: (el: HTMLDivElement | undefined) => void;
  id?: string;
  children?: any;
}

export function VistaView(props: VistaViewProps) {
  let container: HTMLDivElement | undefined;
  let instance: VistaInterface | null = null;
  const [local, rest] = splitProps(props, ['selector', 'options', 'vistaRef', 'ref', 'id', 'children']);
  const galleryId = local.id || `vvw-gallery-${Math.random().toString(36).slice(2)}`;

  onMount(() => {
    if (!container) return;
    instance = vistaView({
      ...local.options,
      elements: `#${galleryId} ${local.selector ?? '> a'}`,
    });
    local.vistaRef?.(instance);
    local.ref?.(container);
  });

  createEffect(() => {
    // If options, selector, or children change, re-instantiate
    instance?.destroy();
    instance = vistaView({
      ...local.options,
      elements: `#${galleryId} ${local.selector ?? '> a'}`,
    });
    local.vistaRef?.(instance);
  });

  onCleanup(() => {
    instance?.destroy();
    local.vistaRef?.(null);
    instance = null;
  });

  return (
    <div ref={el => (container = el)} id={galleryId} {...rest}>
      {local.children}
    </div>
  );
}

// frameworks/react/src/vistaview.tsx
import { useEffect, useRef, useId, useImperativeHandle } from 'react';
import type { ReactNode } from 'react';
import { vistaView } from 'vistaview';
import type { VistaInterface, VistaOpt } from 'vistaview';

export interface VistaViewProps {
  children: ReactNode;
  selector?: string;
  options?: VistaOpt;
  vistaRef?: React.Ref<VistaInterface>;
  ref?: React.Ref<HTMLDivElement>;
}

export function VistaView({ children, selector = '> a', options, id, ref, vistaRef, ...rest }: VistaViewProps & React.HTMLAttributes<HTMLDivElement>) {
  const containerRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<VistaInterface | null>(null);
  const generatedId = useId();
  const galleryId = id || `vvw-gallery-${generatedId.replace(/:/g, '')}`;

  useImperativeHandle(vistaRef, () => instanceRef.current!, []);
  useImperativeHandle(ref, () => containerRef.current!, []);

  useEffect(() => {
    if (!containerRef.current) return;

    instanceRef.current = vistaView({
      ...options,
      elements: `#${galleryId} ${selector}`,
    });

    return () => {
      instanceRef.current?.destroy();
      instanceRef.current = null;
    };
  }, [galleryId, selector, options, children]);

  return (
    <div ref={containerRef} {...rest} id={galleryId}>
      {children}
    </div>
  );
}
