// frameworks/svelte/src/lib/VistaView.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte';
  import { vistaView } from 'vistaview';
  import type { VistaOpt, VistaInterface } from 'vistaview';
  import { tick } from 'svelte';

  export let selector: string = '> a';
  export let options: VistaOpt = {} as VistaOpt;
  export let id: string = '';
  export let vistaRef: ((obj: { vistaView: VistaInterface | null; container: HTMLElement | null } | null) => void) | undefined;

  let container: HTMLDivElement | null = null;
  let instance: VistaInterface | null = null;
  const galleryId = id || `vvw-gallery-${Math.random().toString(36).slice(2)}`;

  function destroyInstance() {
    instance?.destroy();
    instance = null;
    vistaRef?.(null);
  }

  function initInstance() {
    if (!container) return;
    destroyInstance();
    instance = vistaView({
      ...options,
      elements: `#${galleryId} ${selector}`,
    });
    vistaRef?.({ vistaView: instance, container });
  }

  // expose API via component instance
  export function getApi() {
    return { vistaView: instance, container };
  }

  // re-init when props change
  $: selector, options, async () => {
    // wait DOM update if necessary
    await tick();
    initInstance();
  };

  let observer: MutationObserver | null = null;
  let observerTimer: number | null = null;

  onMount(() => {
    initInstance();

    if (container) {
      observer = new MutationObserver(() => {
        if (observerTimer) clearTimeout(observerTimer);
        observerTimer = window.setTimeout(() => initInstance(), 50) as unknown as number;
      });
      observer.observe(container, { childList: true, subtree: true });
    }
  });

  onDestroy(() => {
    observer?.disconnect();
    if (observerTimer) clearTimeout(observerTimer);
    destroyInstance();
  });
</script>

<div id={galleryId} bind:this={container} {...$$restProps}>
  <slot />
</div>

// frameworks/vue/src/vistaview.vue
<script lang="ts">
import { defineComponent, ref, onMounted, onBeforeUnmount, computed, watch, nextTick } from 'vue';
import { vistaView } from 'vistaview';
import type { VistaInterface, VistaOpt } from 'vistaview';

export default defineComponent({
  name: 'VistaView',
  props: {
    selector: { type: String, default: '> a' },
    options: { type: Object as () => VistaOpt, default: () => ({}) },
    id: { type: String, default: '' },
  },
  setup(props, { expose }) {
    const containerRef = ref<HTMLElement | null>(null);
    const instanceRef = ref<VistaInterface | null>(null);
    const generatedId = Math.random().toString(36).slice(2, 9);
    const galleryId = computed(() => (props.id || `vvw-gallery-${generatedId}`));

    // API object to expose and optionally assign to the passed `vistaRef` prop
    const api = {
      open: (i = 0) => instanceRef.value?.open(i),
      close: () => instanceRef.value?.close?.() ?? Promise.resolve(),
      reset: () => instanceRef.value?.reset(),
      next: () => instanceRef.value?.next(),
      prev: () => instanceRef.value?.prev(),
      zoomIn: () => instanceRef.value?.zoomIn(),
      zoomOut: () => instanceRef.value?.zoomOut(),
      getCurrentIndex: () => instanceRef.value?.getCurrentIndex?.() ?? -1,
      view: (i: number) => instanceRef.value?.view(i),
      destroy: () => instanceRef.value?.destroy(),
    } as unknown as VistaInterface;

    // helper to initialize the instance; destroys previous instance if any
    function initInstance() {
      if (!containerRef.value) return;
      instanceRef.value?.destroy();
      instanceRef.value = vistaView({
        ...(props.options as VistaOpt),
        elements: `#${galleryId.value} ${props.selector}`,
      });
    }

    let observer: MutationObserver | null = null;
    let observerTimer: number | null = null;

    onMounted(() => {
      // initial instantiation
      initInstance();

      // watch for DOM changes inside the gallery (slot changes) and re-init (debounced)
      if (containerRef.value) {
        observer = new MutationObserver(() => {
          if (observerTimer) window.clearTimeout(observerTimer);
          observerTimer = window.setTimeout(() => {
            initInstance();
          }, 50);
        });
        observer.observe(containerRef.value, { childList: true, subtree: true });
      }

    });

    onBeforeUnmount(() => {
      observer?.disconnect();
      if (observerTimer) window.clearTimeout(observerTimer);
      instanceRef.value?.destroy();
      instanceRef.value = null;

    });

    // watch props for changes and re-initialize
    watch(() => props.selector, () => {
      nextTick(() => initInstance());
    });

    watch(() => props.options, () => {
      nextTick(() => initInstance());
    }, { deep: true });

    // also expose API and DOM on the component instance for users who use `ref` on the component
    // expose: { vistaView, container } where `container` is a live getter to the DOM element
    expose({
      vistaView: api,
      get container() {
        return containerRef.value;
      },
    });

    return { containerRef, galleryId };
  },
});
</script>

<template>
  <div :id="galleryId" ref="containerRef" v-bind="$attrs">
    <slot />
  </div>
</template>
